### ISSUE TITLE
Contact & About Page

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#13]

**Comment by DeeMcCart** [comment]
Hi Caylin I am looking at the 'About' page today Sunday (brought it back to a separate page that won't affect intensive styling work being done by Kayla & Nikola

![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/084f171f-7ddf-478a-a0b0-2c219f78bcd2)
