### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#17]

**Comment by DeeMcCart** [comment]
Front-end deploy done successfully by Kayla Sunday 21/01/24 - site link is https://kaylaesmith1.github.io/budget_busters/index.html#
Despite lots of time spent on back-end deploy Deirdre was not successful by Sunday 21/01/24 and (reluctantly) moved on to other tasks.  (Reached a succesful deploy but site kept crashing on load)
Further work on attempting back-end deploy can be done in Deirdre's own time.

In fact, the front-end app deployed holds persistent data so the fundamental goal of storing user information across multiple days has been achieved in the deployed solution.
