### ISSUE TITLE
Manual Tests

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#19]

**Comment by DeeMcCart** [comment]
significant manual testing done during developent, and, more formally, done Sunday evening.  Screeenprints are in images folder and clearly follow workflows through from start to conclusion.      The showcase video also covers these processes.   Defensive design was done as part of the development process, so, for example, a letter cannot be entered into a number field.  Example below shows 4 steps in the seqeuence of creating a user budget.

**Comment by DeeMcCart** [comment]
![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/0821ec87-28ab-40a1-8389-38aaa507ca06)



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/b62213ea-9acd-4b9e-aa2c-499ddbf19ccb)



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/04894286-5950-4970-8ec2-936d8dd961bc)



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/962aaacc-1b9a-4798-b910-72e18be6709b)
