### ISSUE TITLE
Text for ABOUT PAGE

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#35]
As the **developer**, I can **write an about section telling how to use the app and what the features are** so that **users can use the application easily**.

**Comment by DeeMcCart** [comment]
done but in very simple form... would like to have put a bit more here.... 

![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/a736841e-a8a9-4a78-9385-25936bfdab29)
