### ISSUE TITLE
FTU04 - Ensure app informs user to increase financial awareness

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#57]
As a **first-time user**, I want **to increase my financial awareness** so that **I can improve my personal financial circumstances**.

**Comment by DeeMcCart** [comment]
This one set aside for Version2.  Definitely have the page (possibly the 'about' and 'insights' pages) which can be used as a base for this.  Just a bigger development requirement than the time available.
