### ISSUE TITLE
FTU05 - Application responsiveness

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#58]
As a **first-time user**, I want **this application to be responsive to access this site on a device of my choosing (mobile, tablet, laptop, desktop)** so that **I can access it properly on a device of my choosing (mobile, tablet, laptop, desktop)**.

**Comment by DeeMcCart** [comment]
![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/7e84caf2-4751-4b3a-8101-3f01bf6e54fd)
