### ISSUE TITLE
RU01 - Ability to enter financial goals

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#59]
As a **returning user**, I want **to enter my financial goals** so that **I can target what's important to me personally**.

**Comment by DeeMcCart** [comment]
Done (one of the last-day features!)

![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/fb1b0def-c38c-4c61-aaa1-ec027edbc6e4)
