### ISSUE TITLE
RU02 - Spending diary ability

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#60]
As a **returning user**, I want **to create a spending diary** so that **I can track my spending over time**.

**Comment by DeeMcCart** [comment]
Deirdre (design)  & Nikola (development) - done well and this is now the core of the site

![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/5015efc8-b195-45ec-8a18-3664996adf58)



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/ffdd76d2-ef16-4f64-bfb0-a68ddd4733bd)



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/03d60233-3400-4b30-96be-089c8601fda5)
