### ISSUE TITLE
RU03 - Ability to create usernames

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#61]
As a **returning user**, I can **to save data under my username** so that **I can access my saved goals and spending history on subsequent site visits**.

**Comment by DeeMcCart** [comment]
DONE via workaround - a device will retain user data over time, so the user information can be retrieved and used, e.g. for spend analysis

![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/c7e1180b-b427-4efb-b219-c9d12ddd25c4)
