### ISSUE TITLE
RU04 - Ability to set monthly spending budget

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#63]
As a **returning user**, I want **to set a monthly spending budget** so that **I know what amount is available to me**.

**Comment by DeeMcCart** [comment]
DONE & DELIVERED



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/964e178d-45ec-4534-9779-90e079801c3f)



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/01abce55-06a6-4284-a787-7a3dc75439c1)
