### ISSUE TITLE
RU05 - Breakdown user spending by category

### ISSUE THREAD

**Issue by Kaylaesmith1** [Kaylaesmith1/budget_busters#64]
As a **returning user**, I want **to see a breakdown of my spending by category** so that ** I can gain insights into my spending**.

**Comment by DeeMcCart** [comment]
DONE THOROUGHLY

![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/2991f2ae-958d-4fa5-b5db-c4b15badd1c4)



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/c0e3b643-2246-49e0-87fa-58ea203cf2ec)



![Image](https://github.com/Kaylaesmith1/budget_busters/assets/126502176/42597013-761d-41f6-9ed2-5d020c861411)
