### ISSUE TITLE
Readme File Requirements

### ISSUE THREAD

**Issue by DeeMcCart** [Kaylaesmith1/budget_busters#76]
A. One sentence for each project goal 
- 1. Problem statement: As a user I want to be able to ... to .....; 
- 2. Objective: The main objective is to ... that .... 
- 3. Target Audience: The target audience is ...  
- 4. Benefits: The benefits are...
B. Future Implementations, 
C. Tech Stack, 
D. Media Frameworks, Libraries & Programs Used
E. API URL and name
f. Wireframes images

**Comment by DeeMcCart** [comment]
Ref issue #47 Caylin for the user stories,

I would say the main objective is to provide a low-cost, responsive, fully-accessible financial tracker and planner, and to help users achieve their financial goals.

Target audience:  I think target audience is users who have access to a smartphone or larger-screen device, who have an income (we are currently thinking in terms of monthly income) which is their spending budget, and who are willng to spend time gathering, tracking and inputting their spending data, in order to get insights on spending patterns and track progress towards their financial goals.

Tech Stack: 
Google sheets backend
Flask (python bridge between front and back-end)

Implementation experience with Google Sheets backend:
Google sheets backend - this was chosen as it was felt that this app should really have a way of saving data so that a returning user can enter spending data, in particular, over a period of time.
One way (perhaps a final solution) would be to build this using Django frameworks which support full database and authentication functionality.  To reduce deployment complexity, we opted for Google sheets.  This has embarked us on a learning curve with Flask (used as the bridge between HTML and Python)

In practice deployment of the GoogleSheets backend has also proven to be quite complex and forces us down a python-first route whereby python is the core app for our deployment, and the html sheets are effectively called from within the python app.  This is proving tricky to coordinate as Front-end development by our team is directly within html/css which then needs to be ported across to our python dev environment (basically a copy of the index file placed into a templates folder with additional calls to the Flask backend).

As of Saturday afternoon we ar still working on successfully deploying this python instance to CRUD our GoogleSheets dataset from within our front-end app.

**Comment by CaylinDewey** [comment]
Thank you - this is very helpful (-:
